### ISSUE TITLE
Code execution error

### ISSUE THREAD

**Issue by tuoniaoren** [changwoolee/WGAN-GP-tensorflow#1]
I run your code using my data,but always error.I don't know what is wrong.

**Comment by changwoolee** [comment]
Did you use CelebA dataset?

This project currently supports celeba only.

The celeba datasets should be located here:

`PRJ_DIR/data/img_align_celeba/*****.jpg`

Thanks.

**Comment by tuoniaoren** [comment]
sorry,i use my data,not celeba.thanks for your code

**Comment by lzzlxxlsz** [comment]
> sorry,i use my data,not celeba.thanks for your code
have you run the code successfully with your dataset?
